export const CLASSIFICATION = {
  MAJOR: 1,
  SIGNIFICANT: 2,
  STANDARD: 3,
  NORMAL: 4,
} as const;

export const CLASSIFICATION_LABELS: Record<number, string> = {
  [CLASSIFICATION.MAJOR]: 'Major',
  [CLASSIFICATION.SIGNIFICANT]: 'Significant',
  [CLASSIFICATION.STANDARD]: 'Standard',
  [CLASSIFICATION.NORMAL]: 'Normal',
};

export const CLASSIFICATION_SELECT_OPTIONS = [
  { value: CLASSIFICATION.STANDARD, label: CLASSIFICATION_LABELS[CLASSIFICATION.STANDARD] },
  { value: CLASSIFICATION.MAJOR, label: CLASSIFICATION_LABELS[CLASSIFICATION.MAJOR] },
  { value: CLASSIFICATION.SIGNIFICANT, label: CLASSIFICATION_LABELS[CLASSIFICATION.SIGNIFICANT] },
  { value: CLASSIFICATION.NORMAL, label: CLASSIFICATION_LABELS[CLASSIFICATION.NORMAL] },
];
